global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spark'
    static_configs:
      - targets: ['spark:9091']
    metrics_path: '/metrics'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9404']
    metrics_path: '/metrics'

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'backend'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['backend:8001']

  - job_name: 'ml_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ml_service:8000']